ListOfMatches date search, ListOfStudents activity column, Register page bugfix
Tandem-App-Tuni/Kivako-App pull request #81
Opened 2021-03-31 17:57 UTC by EAkkanen

1) ListOfMatches admin page date range search feature
Many changes required for this one. Three new DOM elements were added: 2 datepickers and a "reset dates" button. Various new methods were needed to support date range filtering (handleToDateChange, handleFromDateChange, compareDateRange, onResetDates). The "handleSearchChange" method was replaced with "handleAllSearchChanges" that filters the results twice, based on the textfield search criteria as well as the date range criteria.

2) ListOfStudents admin page shows student activity
The column for user activity now correctly displays the user's activity status with either a check icon or a red X (called a "close icon" in MUI).

3) Register page/Sign up page bugfix
A simple fix for a small bug. Previously it was possible for a new user to choose the same language multiple times for "want to learn".

2021-04-05 13:28 UTC, renata-papp approved these changes

2021-04-06 16:42 UTC, janakavishwajith requested changes
Some smaller changes to be done....

2021-04-06 16:42 UTC, janakavishwajith commented on src/containers/ListOfMatches/index.js
> +      console.log("searchValue's setState completed", this.state);
Please remove the console.logs, it doesn't looks nice on production.. :P

2021-04-06 16:42 UTC, janakavishwajith commented on src/containers/ListOfMatches/index.js
> +    if(isAfter(targetdate, date1) || isEqual(targetdate, date1)){
This logic could be more simplified...
Not a mandatory change

2021-04-06 16:42 UTC, janakavishwajith commented on src/containers/ListOfMatches/index.js
> +      console.log("handleFromDateChange's setState completed", this.state);
Please remove the console logs

2021-04-06 16:42 UTC, janakavishwajith commented on src/containers/ListOfMatches/index.js
> +      console.log("handleToDateChange's setState completed", this.state);
More logs to remove

2021-04-06 19:12 UTC, EAkkanen commented
Made Janaka's requested changes of removing console logs for asynchronization checks.
Added a maxDate value to "to-date" as well that limits the latest selectable date to "current date".

2021-04-06 20:25 UTC, janakavishwajith approved these changes

2021-04-06 20:33 UTC, merged